### ISSUE TITLE
Only GPU ID '0' working

### ISSUE THREAD

**Issue by sachinmotwani20** [microsoft/Semi-supervised-learning#101]
## Bug
While the code works perfectly when I use the default GPU (with GPU ID '0'), I have been trying to use a different GPU than GPU ID '0'. This gives the following error.
### Error Messages and Logs

> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:4 and cuda:0! (when checking argument for argument weight in method wrapper__cudnn_convolution)

I anticipate that somewhere in the code (that I am unable to locate), the **GPU ID is hardcoded to '0'**, which throws some data in GPU '0' and the remaining to the mentioned GPU (say) '4'.
Alternately, the **GPU ID is not being updated** in that particular segment of the code, and hence it is taking the default GPU.

Please correct me if I am wrong. All I am doing to update the GPU ID is making changes in the 'gpu' of config.

**Comment by Hhhhhhao** [comment]
I usually use `CUDA_VISIBLE_DEVICES=GPU_ID python train.py` instead of setting gpu in config files. Setting gpu number in config files can cause the problem you mentioned since in some code we use `tensor.cuda()` as default instead of `tensor.cuda(self.gpu)`. 

This might be a design flaw, and we will consider fix this in the next update.

**Comment by sachinmotwani20** [comment]
> `CUDA_VISIBLE_DEVICES=GPU_ID python train.py`  
This works for me. Thanks!
