### ISSUE TITLE
Low results on CIFAR-100 with classic CV implementations

### ISSUE THREAD

**Issue by AurelienGauffre** [microsoft/Semi-supervised-learning#105]
Hi,
Firstly, I'd like to thank you for your dedication and work on this library.
I have been successful in reproducing the results from the [USB CV Classic benchmark](https://github.com/microsoft/Semi-supervised-learning/blob/main/results/classic_cv.csv) on both CIFAR-10 and CIFAR-100, using FixMatch and FlexMatch. On CIFAR-10, the results align well with the ones obtained from your previous library, [Torch SSL](https://github.com/TorchSSL/TorchSSL/blob/main/README.md) (same results as [FlexMatch paper](https://arxiv.org/pdf/2110.08263.pdf) since it's the official implementation).

However, I noticed a significant disparity in the results for CIFAR-100. I've reported the error rates in the following tables:
### CIFAR-10 and CIFAR-100 Error Rates (%)
| Model | CIFAR-10 | | | CIFAR-100 | | |
|---|---|---|---|---|---|---|
| | 40 | 250 | 4000 | 400 | 2500 | 10000 |
| FixMatch (TorchSSL/Flexmatch paper) | 7.47 | 4.86 | 4.21 | 46.42 | 28.03 | 22.2 |
| FixMatch (USB) | 8.33 | 4.97 | 4.29 | **53.37** | **34.29** | **28.28** |
| FlexMatch (TorchSSL/Flexmatch paper) | 4.97 | 4.98 | 4.19 | 39.94 | 26.49 | 21.9 |
| FlexMatch (USB) | 5.21 | 5.0 | 4.28 | **50.15** | **33.35** | **27.12** |

(Note: I have omitted std for clarity, and the Top-1 accuracies have been converted to error rates.)

A similar difference also appears to be present in other results reported in the literature for CIFAR-100, such as those for FreeMatch, CoMatch, and so on. Could there be any underlying reasons for this discrepancy, do you think there might be an implementation issue related with CIFAR-100, or did I miss something ? 
Thank you in advance for your answer.

**Comment by Hhhhhhao** [comment]
Hi, I think the low USB results on CIFAR-100 is because we are using wrn_28_2 for now in USB on CIFAR-100: https://github.com/microsoft/Semi-supervised-learning/blob/9a24e00db040443b4b8d13ecb556b6948c56d15e/config/classic_cv/comatch/comatch_cifar100_400_0.yaml#L38.
Whereas TorchSSL still use wrn_28_8. We choose wrn_28_2 for now to get some initial results to validate the library is working. 
We will update the wrn_28_8 resources in the following months once we get more computing resources.
