### ISSUE TITLE
A wrong implementation in training data sampling

### ISSUE THREAD

**Issue by qfkkwgd** [microsoft/Semi-supervised-learning#22]
## Bug

I believe there is an error in semilearn/datasets/utils.py: Line 100. 

### Reproduce the Bug

Here is the line 100: ulb_idx.extend(idx[lb_samples_per_class[c]:lb_samples_per_class[c]+ulb_samples_per_class[c]])

If I am not wrong, this line means to construct unlabeled data for training.
The variable "ulb_samples_per_class" is simply obtained by (total number of training data /number of class). However, the dataset may not be exactly balanced. For example, let's consider a binary class task with 1000 positive data points and 1200 negative data points. In this case, "ulb_samples_per_class" should be (1,000 + 1,200) / 2 = 1,100. And the total unlabeled data should be 2,200.

However, if line 100 is conducted, only 2,100 unlabeled data is collected.

**Comment by Hhhhhhao** [comment]
Hi, thanks for pointing this out.

However, this would be a problem because most of the data settings we support are balanced and thus would be affected by the example you have here. 

We do find two datasets will be affect, eurosat and tissuemnist, if you are using that two dataset, the total number of unlabeled would be affected.

**Comment by qianlanwyd** [comment]
We will fix this bug soon.

**Comment by Hhhhhhao** [comment]
Bug fixed in
https://github.com/microsoft/Semi-supervised-learning/commit/d81cee9d6075c1123c65ce04894e658dfa8bd8d1
