### ISSUE TITLE
Failed to reproduce results

### ISSUE THREAD

**Issue by syorami** [microsoft/Semi-supervised-learning#35]
I'm trying to reproduce the result of FlexMatch on CIFAR100-400 experiment and only got around 56% acc, which is less than the reported result 60%. I simply use the command `python train.py --c config/classic_cv/flexmatch/flexmatch_cifar100_400_0.yaml` and here is my training curve:

![screenshot-20221121-115003](https://user-images.githubusercontent.com/11853126/202961800-7387c907-ac8b-4510-b25a-a5f2e7fddf29.png)

Is there sth I've missed?

**Comment by Hhhhhhao** [comment]
According to our previous training logs, the best accuracy of FlexMatch on CIFAR-100 with 400 labels is around 56-57 (at around 500k iteration and decrease after that). So I think your training curve looks fine. 

Besides, the results about classic setting is outdated, we have not updated it since running whole classic setting is very time consuming and expensive. But we will provide an updated version of the classic results at the next update of USB.

**Comment by syorami** [comment]
When will the next update come at? If the code is already ready, maybe I could help run the experiment cause I've been recently focusing on reproducing the SSL methods.

BTW, the results should be marked **outdated** in readme for clarification.

**Comment by Hhhhhhao** [comment]
The next update is expected come at Dec. with imbalanced ssl algorithms (probably openset ssl algorithms) and some small mechanism change for base ssl algorithms.

The reason I say it is outdated is because we have not run the classic results again since [this commit](https://github.com/microsoft/Semi-supervised-learning/commit/50bafa5cadd2c63b7feb8f86cba50a708e7b8445). 
But the results would also be quite similar to the reported one as shown in the excel. 

We are planning rerun the classic setting after settling down the next update, and you are very welcome to help us run experiments. If you are focusing on reproducing the results, you are also welcome to include more recent base algorithms into USB.

**Comment by syorami** [comment]
Nice. Please feel free to contact me. I'm also curious about imbalanced and ood settings in SSL.

**Comment by MemoriesJ** [comment]
Hi Hao,

May I ask will the FreeMatch will be also included in the next commit?
