### ISSUE TITLE
pretrained model didn't get imporved

### ISSUE THREAD

**Issue by janeLing227** [microsoft/Semi-supervised-learning#39]
when used the same parameters in the config/.../stl10_40_0.yaml(vit/wrn)
the precision and top1-accuracy didn't increased, but drop from **0.65 to 0.45**(20k iters)
simmatch and fixmatch had the same problems. had i done some incorrect?
the result used the original code.

**Comment by Hhhhhhao** [comment]
It is expected that the accuracy drops with ViT on STL10-40 due to the checkpoint used is from MAE. Our log also shows the performance degradation during training of STL10. 

But if you are using WRN in classic setting, I think the performance should increase during training (or at least the first half of training.)

**Comment by twmht** [comment]
@Hhhhhhao 

How did you train the pretrained weight? what is `MAE`?

**Comment by Hhhhhhao** [comment]
Fixed in 69a2afc8ecc9ec29cbf6afb123035d2be3443568
